spring:
  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://192.168.100.202:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zhiran_test
    password: Zhiran123

# mybatis 配置内容
mybatis:
  config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: com.dragon.mybatisxml.entity # 配置数据库实体包路径
