spring:
  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://192.168.100.202:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zhiran_test
    password: Zhiran123
